apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-consumer
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: event-consumer
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: event-consumer
          image: github.com/wlynch/knative-test/consumer
 ---

# Service pointing at the previous Deployment. This will be the target for event
# consumption.
  kind: Service
  apiVersion: v1
  metadata:
    name: event-consumer
  spec:
    selector:
      app: event-consumer
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
END
