apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: producer-subscription
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: producer-channel
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: event-producer
  reply: 
    channel:
      apiVersion: messaging.knative.dev/v1alpha1
      kind: Channel
      name: consumer-channel
