apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: trigger-producer
spec:
  subscriber:
    ref:
      apiVersion: messaging.knative.dev/v1alpha1
      kind: Channel
      name: producer-channel
