apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: tekton-trigger
spec:
  broker: default
  filter:
    expression: ce.build
  subscriber:
    ref:
      apiVersion: tekton.dev/v1alpha1
      kind: EventListener
      name: getting-started-listener
